add refcoco to llava
InternLM/xtuner pull request #425
Opened 2024-02-21 03:24 UTC by LKJacky

Add refcoco datasets for llava finetune.

It contains three parts.
1. datasets 
2. script to convert refcoco format to json format
3. script to eval refcoco grounding.

2024-02-21 06:37 UTC, LZHgrla commented on docs/en/user_guides/dataset_prepare.md
Please add the data convert step (how to use tools/convert_refcoco) here.
Also, please update the zh_cn docs.

2024-02-21 06:37 UTC, LZHgrla commented on xtuner/configs/llava/vicuna_7b_v15_clip_vit_large_p14_336/finetune/llava_vicuna_7b_v15_qlora_clip_vit_large_p14_336_lora_e1_gpu8_finetune_refcoco.py
> +refcoco_path = data_root + 'data/llava_data/RefCOCOJson/train.json'
Please double-check the json data path.

2024-02-21 06:37 UTC, LZHgrla commented on xtuner/configs/llava/vicuna_7b_v15_clip_vit_large_p14_336/finetune/llava_vicuna_7b_v15_qlora_clip_vit_large_p14_336_lora_e1_gpu8_finetune_refcoco.py
> +    # ),
Shall we use EvaluateChatHook?

2024-02-23 06:16 UTC, pppppM commented on docs/en/user_guides/dataset_prepare.md
> +python xtuner/tools/convert_refcoco.py
```suggestion
xtuner preprocess refcoco
```

2024-02-23 06:16 UTC, pppppM commented on docs/zh_cn/user_guides/dataset_prepare.md
> +python xtuner/tools/convert_refcoco.py
```suggestion
xtuner preprocess refcoco
```

2024-02-23 06:21 UTC, pppppM approved these changes

2024-02-23 06:35 UTC, LZHgrla requested changes

2024-02-23 06:35 UTC, LZHgrla commented on xtuner/entry_point.py
> +        8. Refcoco evaluation:
```suggestion
        9. Refcoco evaluation:
```

2024-02-26 03:32 UTC, LZHgrla approved these changes

2024-02-26 06:55 UTC, merged