[Docs] Add `docs/zh_cn/preparation/pretrained_model.md`
InternLM/xtuner pull request #462
Opened 2024-03-11 11:51 UTC by LZHgrla

2024-03-11 12:18 UTC, pppppM commented on docs/zh_cn/preparation/pretrained_model.md
> +此时模型将会下载至 HuggingFace 的 cache 路径中（默认为`~/.cache/huggingface`）。
如何修改 cache 默认路径？

2024-03-11 12:31 UTC, fanqiNO1 requested changes

2024-03-11 12:31 UTC, fanqiNO1 commented on docs/zh_cn/preparation/pretrained_model.md
> +本节将以下载 internlm-chat-7b 为例，介绍如何快速下载预训练模型的权重。
为什么是一代？

2024-03-11 12:31 UTC, fanqiNO1 commented on docs/zh_cn/preparation/pretrained_model.md
> +此时模型将会下载至 HuggingFace 的 cache 路径中（默认为`~/.cache/huggingface`）。
要不改成 ~/.cache/huggingface/hub ?

2024-03-11 12:32 UTC, MING-ZCH approved these changes

2024-03-11 12:38 UTC, hhaAndroid commented on docs/zh_cn/preparation/pretrained_model.md
> +# 准备预训练模型权重
对于用户来说，他不会很关心有多少种下载方式。用户最关心的是： 如果在国内，你推荐哪一种？如果在国外，你推荐哪一种？ 所以前面应该先写清楚推荐用法。后面才是告诉用户一共有多少种。

2024-03-11 12:45 UTC, pppppM reviewed
通过 snapshot download 或者 from pretrain 自动下载，可能有这两种比较头疼的情况，需要考虑下怎么处理：

1. 权重是通过 model scope 下载的，存到了 modelscope 的默认 cache，但 config 中是使用 HF 的 from pretrain，会去 hf 默认的 cache 找模型
2. 接第一种情况，此时如果想要写物理路径，就变得很麻烦，要写到有 commit id 的那一级目录

2024-03-11 12:46 UTC, MING-ZCH commented on docs/zh_cn/preparation/pretrained_model.md
> +本节将以下载 internlm-chat-7b 为例，介绍如何快速下载预训练模型的权重。
+1，建议考虑二代

2024-03-12 06:33 UTC, KooSung commented on docs/zh_cn/preparation/pretrained_model.md
> +此时模型将会下载至 HuggingFace 的 cache 路径中（默认为`~/.cache/huggingface`）。
我自己从huggingface下载数据或者模型的脚本，下载到指定路径
```python
import argparse
import os
from threading import local
from huggingface_hub import snapshot_download

def parse_args():
    parser = argparse.ArgumentParser(description='Set hugging face model config')
    parser.add_argument('--id', type=str, help='model/dataset id')
    parser.add_argument('--dir', type=str, default=./model/',
                        help='If provided, the downloaded files will be placed under this directory, either as symlinks (default) or regular files.')
    parser.add_argument('--type', type=str, default='model',
                    help='model/dataset')
    args = parser.parse_args()
    return args


def download_weights():
    args = parse_args()
    snapshot_download(
        repo_id=args.id, 
        local_dir=os.path.join(args.dir, os.path.basename(args.id)),
        repo_type=args.type,
        local_dir_use_symlinks=False,
        token=MY_TOKEN)


if __name__ == '__main__':
    download_weights()
```

2024-03-13 12:02 UTC, LZHgrla commented
> 通过 snapshot download 或者 from pretrain 自动下载，可能有这两种比较头疼的情况，需要考虑下怎么处理：
> 
> 1. 权重是通过 model scope 下载的，存到了 modelscope 的默认 cache，但 config 中是使用 HF 的 from pretrain，会去 hf 默认的 cache 找模型
> 2. 接第一种情况，此时如果想要写物理路径，就变得很麻烦，要写到有 commit id 的那一级目录

借鉴了 @KooSung  的做法，现在的下载将直接下载到本地路径，不存在 commit_id 的概念，可以直接使用。

2024-03-13 12:03 UTC, fanqiNO1 approved these changes

2024-03-13 12:03 UTC, LZHgrla commented
根据 comment 更新了一版！ 
辛苦大家 review
@hhaAndroid @KooSung @pppppM @fanqiNO1 @MING-ZCH

2024-03-14 06:11 UTC, hhaAndroid commented on docs/zh_cn/preparation/pretrained_model.md
> +```python
贴一下准备命令 `python -m pip install huggingface_hub`

同时加一下如下内容：

如果觉得下载比较慢，可以设置 `HF_HUB_ENABLE_HF_TRANSFER=1` 获得更高的下载速度。
关于 huggingface_hub 的更多用法可阅读 [这里](https://huggingface.co/docs/huggingface_hub/v0.20.2/package_reference/environment_variables#hfhubenablehftransfer)。

2024-03-14 06:11 UTC, hhaAndroid commented on docs/zh_cn/preparation/pretrained_model.md
> +其中，`repo_id` 表示模型在 HuggingFace Hub 的名字、`local_dir` 表示期望存储到的本地路径、`max_workers` 表示下载的最大并行数。
可以说明下，如果用户没有指定 local_dir，则默认下载到 .cache 路径下，通常为 ~/.cache/huggingface

2024-03-14 06:11 UTC, hhaAndroid commented on docs/zh_cn/preparation/pretrained_model.md
> +export TRANSFORMERS_CACHE=YOUR_CACHE_PATH
这里是否要解释下，为啥要设置两个环境变量？每个环境变量的含义是啥？

2024-03-14 15:34 UTC, fanqiNO1 commented
突然想到的一点，要不要在 HuggingFace `snapshot_download` 部分提一下 `local_dir_use_symlinks`

2024-03-18 09:45 UTC, LZHgrla commented on docs/zh_cn/preparation/pretrained_model.md
> +```python
OK!  关于准备命令，`huggingface_hub` 其实被 `transformers`、`datasets` 等库依赖，所以是否可以不加？ 还是说多多益善，加上更好。

2024-03-18 09:53 UTC, LZHgrla commented
> 突然想到的一点，要不要在 HuggingFace `snapshot_download` 部分提一下 `local_dir_use_symlinks` 这个参数？

我感觉讲的话，选项有点多，会太长了，会把问题搞复杂？

2024-03-18 09:55 UTC, fanqiNO1 commented
> > 突然想到的一点，要不要在 HuggingFace `snapshot_download` 部分提一下 `local_dir_use_symlinks` 这个参数？
> 
> @fanqiNO1 我感觉讲的话，选项有点多，会太长了，会把问题搞复杂？

倒是也合理，应该保持能用就行

2024-03-18 10:20 UTC, LZHgrla commented on docs/zh_cn/preparation/pretrained_model.md
> +export TRANSFORMERS_CACHE=YOUR_CACHE_PATH
统一使用了 `HF_HOME`

2024-03-26 11:55 UTC, pppppM approved these changes

2024-03-26 11:55 UTC, merged