[WIP] Support InternVL finetune
InternLM/xtuner pull request #737
Opened 2024-05-31 12:48 UTC by hhaAndroid

2024-06-21 04:09 UTC, KooSung commented
@hhaAndroid hello，请问这个进度大概完成了多少？什么时候会merge到主分支呢？

2024-06-21 09:40 UTC, hhaAndroid commented
> @hhaAndroid hello，请问这个进度大概完成了多少？什么时候会merge到主分支呢？

已经完成了，你可以直接用，这个就已经是最终形态了

2024-06-25 02:36 UTC, cydiachen requested changes
find one error

2024-06-25 02:36 UTC, cydiachen commented on xtuner/configs/internvl/v1_5/convert_to_official.py
> +        cfg.model.path, trust_remote_code=True)
ConfigDict has no path

2024-06-25 02:37 UTC, hhaAndroid commented on xtuner/configs/internvl/v1_5/convert_to_official.py
> +        cfg.model.path, trust_remote_code=True)
ok

2024-06-25 12:30 UTC, cydiachen approved these changes

2024-07-10 08:31 UTC, sunzjz commented
请问最新VL40B的模型支持吗

2024-07-17 12:32 UTC, bjzhb666 commented
![image](https://github.com/user-attachments/assets/45fc3df5-2b00-4c5f-9141-4cc4d9d38ba9)
没有找到internvl的文件夹呢？请问现在可以用吗？

2024-07-18 11:42 UTC, BIGBALLON commented
同问，，config下似乎没有internvl的文件夹？

2024-07-22 06:44 UTC, pppppM approved these changes

2024-07-22 06:45 UTC, merged